# Generated by Django 4.0.4 on 2022-05-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Adim', max_length=60),
            preserve_default=False,
        ),
    ]
